"""Memory v2 workflow contracts.

These small value objects separate the lifecycle decisions from storage and
retrieval implementations.  They are intentionally independent of LangGraph
and database models so the workflow can be tested in isolation.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class CompletedTurn(BaseModel):
    """A user/assistant turn that is safe to process asynchronously."""

    turn_id: str
    session_id: str
    user_text: str
    assistant_text: str = ""
    user_message_id: str | None = None
    assistant_message_id: str | None = None
    completed_at: datetime = Field(default_factory=datetime.now)


class MemoryWriteTriggerResult(BaseModel):
    """Result of the cheap, non-LLM write trigger."""

    should_extract: bool
    reason: str = ""


class MemoryCandidate(BaseModel):
    """A semantic fact awaiting resolution against existing memories."""

    content: str
    memory_type: str = "fact"
    category: str = "fact"
    confidence: float = 0.8
    source_turn_id: str
    evidence: list[str] = Field(default_factory=list)


class ResolutionAction(StrEnum):
    CREATE = "create"
    UPDATE = "update"
    SUPERSEDE = "supersede"
    IGNORE = "ignore"


class MemoryRelationType(StrEnum):
    SUPERSEDES = "supersedes"
    CONTRADICTS = "contradicts"
    SUPPORTS = "supports"


class MemoryResolution(BaseModel):
    """A storage-neutral decision produced by the candidate resolver."""

    action: ResolutionAction
    candidate: MemoryCandidate
    target_memory_id: str | None = None
    final_content: str | None = None
    reason: str = ""
    relation_type: MemoryRelationType | None = None


class MemoryRetrievalRequest(BaseModel):
    """Explicit read request generated by Agent Runtime."""

    query: str
    limit: int = Field(default=8, ge=1, le=100)
    record_access: bool = True
    session_id: str | None = None
    agent_run_id: str | None = None
    message_id: str | None = None
