"""Storage ports consumed by the memory application service."""

from __future__ import annotations

from typing import Any, Protocol


class MemoryRepository(Protocol):
    async def add(self, record: dict[str, Any]) -> None: ...
    async def flush_access_stats(self, stats: dict[str, Any], expires_at: str) -> list[dict[str, Any]]: ...
    async def keyword_search(self, query: str, limit: int, where: dict[str, Any] | None) -> list[dict[str, Any]]: ...
    async def list(self, **filters: Any) -> list[dict[str, Any]]: ...
    async def counts(self) -> dict[str, int]: ...
    async def update_content(self, memory_id: str, content: str) -> str | None: ...
    async def soft_delete(self, memory_ids: list[str]) -> None: ...
    async def set_pin(self, memory_id: str, pinned: bool, expires_at: str | None) -> tuple[bool, str | None] | None: ...
    async def expired_ids(self, now_iso: str) -> list[str]: ...
    async def hard_delete(self, memory_id: str) -> None: ...
    async def restore_deleted(self, memory_ids: list[str]) -> None: ...


class MemoryVectorStore(Protocol):
    async def initialize(self) -> None: ...
    async def add(self, memory_id: str, content: str, metadata: dict[str, Any]) -> None: ...
    async def query(self, query: str, limit: int, where: dict[str, Any] | None) -> dict[str, Any]: ...
    async def get(self, memory_id: str) -> dict[str, Any]: ...
    async def update(self, memory_id: str, content: str | None = None, metadata: dict[str, Any] | None = None) -> None: ...
    async def delete(self, memory_ids: list[str]) -> None: ...
