"""LLM、sandbox 和索引集成端口。"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class LLMPort(Protocol):
    async def invoke(self, messages: list[Any], **kwargs: Any) -> Any: ...
    def count_text_tokens(self, text: str) -> int: ...


class SandboxPort(Protocol):
    async def execute(self, request: Any) -> Any: ...
    def build_mcp_process(self, *, server_name: str, image: str, command: list[str], args: list[str], workspace: Path, env: dict[str, str] | None = None, network_policy: str = "none") -> Any: ...
    async def health(self) -> bool: ...
    async def close_all(self) -> None: ...


class VectorIndexPort(Protocol):
    async def index_attachment(self, attachment: Any, chunks: list[Any]) -> None: ...
    async def delete_attachment(self, attachment_id: str) -> None: ...


class GraphIndexPort(Protocol):
    async def index_attachment(self, attachment: Any, chunks: list[Any]) -> None: ...
    async def delete_attachment(self, attachment_id: str) -> None: ...


__all__ = ["GraphIndexPort", "LLMPort", "SandboxPort", "VectorIndexPort"]
