"""工具和 MCP 持久化端口。"""

from __future__ import annotations

from typing import Protocol

from .entities import MCPServer, MCPServerConfig, ToolConfig, ToolExecutionRequest, ToolExecutionResult


class ToolConfigRepository(Protocol):
    """工具治理配置持久化能力。"""

    async def upsert(self, config: ToolConfig) -> ToolConfig: ...

    async def get(self, tool_name: str) -> ToolConfig | None: ...

    async def list_all(self) -> list[ToolConfig]: ...

    async def update(self, config: ToolConfig) -> ToolConfig: ...


class ToolExecutionPort(Protocol):
    async def execute(self, request: ToolExecutionRequest) -> ToolExecutionResult: ...


class MCPPort(Protocol):
    async def register(self, name: str, config: MCPServerConfig) -> dict[str, object]: ...
    async def unregister(self, name: str) -> None: ...
    async def list_servers(self) -> list[dict[str, object]]: ...
    async def shutdown(self) -> None: ...


class MCPServerRepository(Protocol):
    """MCP 服务端配置持久化能力。"""

    async def upsert(self, server: MCPServer) -> MCPServer: ...

    async def get(self, name: str) -> MCPServer | None: ...

    async def list_all(self) -> list[MCPServer]: ...

    async def delete(self, name: str) -> bool: ...
